services:
  postgres:
    image: postgres:latest
    container_name: project_management_db
    restart: always
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
